apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: monitoring
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9093
          args:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager/
            - name: secrets-volume
              mountPath: /var/run/secrets
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
        - name: secrets-volume
          hostPath:
            path: /var/run/secrets
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: alertmanager
spec:
  type: ClusterIP
  ports:
    - port: 9093
      protocol: TCP
  selector:
    app: alertmanager
