apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'alertmanager@gmail.com'
      smtp_require_tls: false
      slack_api_url: '${SLACK_API_URL}'

    route:
      receiver: 'slack'
      group_by: ['alertname', 'Role', 'Stage']
      group_wait: 30s
      group_interval: 5m

    receivers:
      - name: 'slack'
        slack_configs:
          - channel: '#general'
      - name: 'email'
        email_configs:
          - to: '${GOOGLE_EMAIL_ADDRESS}'
