apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     60s
      evaluation_interval: 60s

    scrape_configs:
    - job_name: 'prometheus'
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:9090
    - job_name: 'k8s-node-exporter'
      kubernetes_sd_configs:
      - role: pod
        api_server:
        namespaces:
          names:
            - monitoring
        tls_config:
          insecure_skip_verify: false
    receivers:
    - name: slack-channel
      slack_configs:
      - channel: #monitoring
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        send_resolved: true
        title: '{{ template "custom_title" . }}'
        text: '{{ template "custom_slack_message" . }}'
