apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: logs
          emptyDir: {}
      containers:
        - name: nginx
          image: nginx:1.16
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: nginx
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
            - name: logs
              mountPath: /var/log/nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
