apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes 2;
    error_log /var/log/nginx/error.log;
    events {
      worker_connections 1024;
    }
    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      upstream grpc-server {
        server grpc-server:50051;
      }

      server {
        listen 80 http2;

        location / {
          grpc_pass grpc://grpc-server;
        }

      }
    }
