apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: api-server
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: mokemoke1015/sample
          ports:
            - containerPort: 80
          ports:
            - name: redis
              containerPort: 6379
          envFrom:
            - secretRef:
                name: redis-secret
            - secretRef:
                name: mysql-secret
