apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
data:
  REDIS_HOST: MTAuMTEwLjY4LjE3Nw==
  REDIS_PORT: NjM3OQ==
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          envFrom:
            - secretRef:
                name: redis-secret
